### ISSUE TITLE
E_MISSING_PARAMETER: Missing parameter clientId expected by oauth2 as 1st parameter

### ISSUE THREAD

**Issue by manishmaharjan69051** [adonisjs/errors#1]
please solve this ... trying to loggin using facebook...

**Comment by thetutlage** [comment]
Can u share a proper description on what code you are writing and what all you have in the config file?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by manishmaharjan69051** [comment]
Not solved... Trying to solve
